modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/D4vide106/MaintenanceUniversal/issues"

[[mods]]
modId="maintenanceuniversal"
version="1.0.0"
displayName="MaintenanceUniversal"
description="Professional maintenance management for Forge/NeoForge servers"
authors="D4vide106"
displayURL="https://github.com/D4vide106/MaintenanceUniversal"
logoFile="logo.png"

[[dependencies.maintenanceuniversal]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.maintenanceuniversal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="SERVER"
